-- Migration: Insert mock spending data
-- Description: Inserts realistic mock data for testing and development
-- Created: 2025-01-XX

-- Insert mock spending data
-- Note: id will be auto-generated by the database using uuid_generate_v4()
INSERT INTO spendings (amount, category, description, date, created_at) VALUES
-- Food & Dining
(12.50, 'Food', 'Lunch at cafe', '2025-01-15 12:30:00', '2025-01-15 12:35:00'),
(45.80, 'Food', 'Grocery shopping', '2025-01-14 18:00:00', '2025-01-14 18:05:00'),
(8.99, 'Food', 'Coffee and pastry', '2025-01-13 09:15:00', '2025-01-13 09:20:00'),
(67.25, 'Food', 'Restaurant dinner', '2025-01-12 19:45:00', '2025-01-12 19:50:00'),
(23.40, 'Food', 'Fast food', '2025-01-11 13:20:00', '2025-01-11 13:25:00'),
(89.50, 'Food', 'Weekly groceries', '2025-01-10 16:30:00', '2025-01-10 16:35:00'),
(15.75, 'Food', 'Breakfast', '2025-01-09 08:00:00', '2025-01-09 08:05:00'),
(34.20, 'Food', 'Lunch with colleagues', '2025-01-08 13:00:00', '2025-01-08 13:05:00'),

-- Transport
(2.50, 'Transport', 'Bus ticket', '2025-01-15 08:30:00', '2025-01-15 08:35:00'),
(15.00, 'Transport', 'Uber ride', '2025-01-14 22:00:00', '2025-01-14 22:05:00'),
(45.00, 'Transport', 'Gas refill', '2025-01-13 14:00:00', '2025-01-13 14:05:00'),
(8.50, 'Transport', 'Train ticket', '2025-01-12 07:15:00', '2025-01-12 07:20:00'),
(12.00, 'Transport', 'Taxi', '2025-01-11 20:30:00', '2025-01-11 20:35:00'),
(3.00, 'Transport', 'Subway pass', '2025-01-10 09:00:00', '2025-01-10 09:05:00'),
(25.00, 'Transport', 'Parking fee', '2025-01-09 10:00:00', '2025-01-09 10:05:00'),

-- Entertainment
(15.99, 'Entertainment', 'Netflix subscription', '2025-01-01 00:00:00', '2025-01-01 00:05:00'),
(45.00, 'Entertainment', 'Movie tickets', '2025-01-13 19:00:00', '2025-01-13 19:05:00'),
(12.50, 'Entertainment', 'Concert ticket', '2025-01-05 20:00:00', '2025-01-05 20:05:00'),
(8.99, 'Entertainment', 'Spotify Premium', '2025-01-01 00:00:00', '2025-01-01 00:05:00'),
(60.00, 'Entertainment', 'Concert', '2025-01-07 21:00:00', '2025-01-07 21:05:00'),
(25.00, 'Entertainment', 'Bowling', '2025-01-11 18:00:00', '2025-01-11 18:05:00'),

-- Shopping
(89.99, 'Shopping', 'New shoes', '2025-01-10 15:00:00', '2025-01-10 15:05:00'),
(45.50, 'Shopping', 'Clothing', '2025-01-08 14:30:00', '2025-01-08 14:35:00'),
(129.99, 'Shopping', 'Electronics', '2025-01-06 16:00:00', '2025-01-06 16:05:00'),
(34.99, 'Shopping', 'Books', '2025-01-12 11:00:00', '2025-01-12 11:05:00'),
(19.99, 'Shopping', 'Accessories', '2025-01-09 13:00:00', '2025-01-09 13:05:00'),
(67.00, 'Shopping', 'Home decor', '2025-01-07 10:00:00', '2025-01-07 10:05:00'),

-- Bills & Utilities
(120.50, 'Bills', 'Electricity bill', '2025-01-05 00:00:00', '2025-01-05 00:05:00'),
(85.00, 'Bills', 'Internet bill', '2025-01-05 00:00:00', '2025-01-05 00:05:00'),
(45.00, 'Bills', 'Phone bill', '2025-01-05 00:00:00', '2025-01-05 00:05:00'),
(150.00, 'Bills', 'Rent', '2025-01-01 00:00:00', '2025-01-01 00:05:00'),
(65.00, 'Bills', 'Water bill', '2025-01-05 00:00:00', '2025-01-05 00:05:00'),

-- Healthcare
(35.00, 'Healthcare', 'Pharmacy', '2025-01-14 10:00:00', '2025-01-14 10:05:00'),
(150.00, 'Healthcare', 'Doctor visit', '2025-01-10 14:00:00', '2025-01-10 14:05:00'),
(25.50, 'Healthcare', 'Vitamins', '2025-01-08 09:00:00', '2025-01-08 09:05:00'),
(12.99, 'Healthcare', 'First aid supplies', '2025-01-06 11:00:00', '2025-01-06 11:05:00'),

-- Education
(299.99, 'Education', 'Online course', '2025-01-03 00:00:00', '2025-01-03 00:05:00'),
(45.00, 'Education', 'Books', '2025-01-11 12:00:00', '2025-01-11 12:05:00'),
(19.99, 'Education', 'E-book', '2025-01-09 20:00:00', '2025-01-09 20:05:00'),

-- Travel
(350.00, 'Travel', 'Hotel booking', '2025-01-02 00:00:00', '2025-01-02 00:05:00'),
(250.00, 'Travel', 'Flight ticket', '2025-01-01 00:00:00', '2025-01-01 00:05:00'),
(45.00, 'Travel', 'Travel insurance', '2025-01-02 00:00:00', '2025-01-02 00:05:00'),
(78.50, 'Travel', 'Restaurant during trip', '2025-01-04 19:00:00', '2025-01-04 19:05:00'),

-- Personal Care
(28.99, 'Personal Care', 'Haircut', '2025-01-12 15:00:00', '2025-01-12 15:05:00'),
(45.00, 'Personal Care', 'Spa treatment', '2025-01-07 16:00:00', '2025-01-07 16:05:00'),
(15.50, 'Personal Care', 'Skincare products', '2025-01-09 14:00:00', '2025-01-09 14:05:00'),

-- Miscellaneous
(5.50, 'Miscellaneous', 'ATM fee', '2025-01-13 10:00:00', '2025-01-13 10:05:00'),
(12.00, 'Miscellaneous', 'Banking fee', '2025-01-01 00:00:00', '2025-01-01 00:05:00'),
(8.00, 'Miscellaneous', 'Charity donation', '2025-01-08 12:00:00', '2025-01-08 12:05:00'),

-- December 2024 data
(95.00, 'Food', 'Holiday groceries', '2024-12-24 15:00:00', '2024-12-24 15:05:00'),
(120.00, 'Shopping', 'Christmas gifts', '2024-12-20 14:00:00', '2024-12-20 14:05:00'),
(200.00, 'Entertainment', 'New Year party', '2024-12-31 22:00:00', '2024-12-31 22:05:00'),
(55.00, 'Transport', 'Holiday travel', '2024-12-23 08:00:00', '2024-12-23 08:05:00'),
(75.00, 'Food', 'Restaurant', '2024-12-25 19:00:00', '2024-12-25 19:05:00'),

-- November 2024 data
(42.30, 'Food', 'Grocery shopping', '2024-11-15 17:00:00', '2024-11-15 17:05:00'),
(18.50, 'Food', 'Lunch', '2024-11-20 13:00:00', '2024-11-20 13:05:00'),
(30.00, 'Transport', 'Gas', '2024-11-10 12:00:00', '2024-11-10 12:05:00'),
(99.99, 'Shopping', 'Black Friday deal', '2024-11-29 10:00:00', '2024-11-29 10:05:00'),
(35.00, 'Entertainment', 'Movie', '2024-11-18 20:00:00', '2024-11-18 20:05:00');

-- Verify the insert
SELECT 
    category,
    COUNT(*) as count,
    SUM(amount) as total_amount,
    AVG(amount) as avg_amount
FROM spendings
GROUP BY category
ORDER BY total_amount DESC;

